In [1]:
import torch

indices = torch.LongTensor([[0, 1, 1], [2, 0, 2]])
values = torch.FloatTensor([1.0, 2.0, 3.0])
# 创建稀疏矩阵
sparse_matrix = torch.sparse.FloatTensor(indices, values, torch.Size([3, 3]))
sparse_matrix = sparse_matrix.coalesce()
sparse_matrix



/root/miniconda3/envs/fs_gnn/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([1., 2., 3.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

In [18]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
a = torch.stack((a,b), dim=0)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [2]:
# 创建稠密矩阵
dense_matrix = sparse_matrix.to_dense()
dense_matrix


tensor([[0., 0., 1.],
        [2., 0., 3.],
        [0., 0., 0.]])

In [20]:
torch.Size((1,2))

torch.Size([1, 2])

In [28]:
# 重复的元素

indices = torch.LongTensor([[0, 1, 1, 0], [2, 0, 2, 2]])
values = torch.FloatTensor([1.0, 2.0, 3.0, 1.0])
# 创建稀疏矩阵
sparse_matrix = torch.sparse.FloatTensor(indices, values, torch.Size([3, 3]))
sparse_matrix = sparse_matrix.coalesce()
sparse_matrix



tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([2., 2., 3.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

In [25]:
# [int,:]
sparse_matrix[0].to_dense()

tensor([0., 0., 2.])

In [4]:
# [:,int]
# print(sparse_matrix[:,0].to_dense())


In [5]:
# [int,int]
sparse_matrix[1,2]


tensor(3.)

In [6]:
# [tensor,:]
print(sparse_matrix.index_select(0, torch.LongTensor([0])).to_dense())


tensor([[0., 0., 1.]])


In [7]:
# [:,tensor]
print(sparse_matrix.index_select(1, torch.LongTensor([0])).to_dense())


tensor([[0.],
        [2.],
        [0.]])


In [8]:
# [tensor,tensor]
print(sparse_matrix.index_select(0, torch.LongTensor([0,1])).index_select(1, torch.LongTensor([0,1])).to_dense())


tensor([[0., 0.],
        [2., 0.]])


In [11]:
sparse_matrix = sparse_matrix.coalesce()
print(sparse_matrix.layout)
sparse_matrix.index_fill_(0,torch.LongTensor([0]),torch.LongTensor([1]))
# sparse_matrix = sparse_matrix.coalesce()
# sparse_matrix.to_dense()

torch.sparse_coo


NotImplementedError: Could not run 'aten::index_fill_.int_Tensor' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::index_fill_.int_Tensor' is only available for these backends: [CPU, CUDA, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/build/aten/src/ATen/RegisterCPU.cpp:30798 [kernel]
CUDA: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/build/aten/src/ATen/RegisterCUDA.cpp:43635 [kernel]
Meta: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/build/aten/src/ATen/RegisterMeta.cpp:26815 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/core/PythonFallbackKernel.cpp:140 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/functorch/DynamicLayer.cpp:488 [backend fallback]
Functionalize: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/build/aten/src/ATen/RegisterFunctionalization_3.cpp:22330 [kernel]
Named: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
Conjugate: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/ADInplaceOrViewType_1.cpp:5089 [kernel]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradHIP: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradMPS: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradIPU: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradXPU: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradVE: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradLazy: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradMeta: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
AutogradNestedTensor: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/VariableType_2.cpp:16915 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/torch/csrc/autograd/generated/TraceType_1.cpp:15586 [kernel]
AutocastCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/autocast_mode.cpp:482 [backend fallback]
AutocastCUDA: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/autocast_mode.cpp:324 [backend fallback]
FuncTorchBatched: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:743 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/BatchingRegistrations.cpp:1064 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/functorch/TensorWrapper.cpp:189 [backend fallback]
PythonTLSSnapshot: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/functorch/DynamicLayer.cpp:484 [backend fallback]
PythonDispatcher: registered at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]


In [ ]:

i = torch.tensor([[0, 1, 0, 2],[0, 1, 2, 0]])
v = torch.tensor([1, 5, 7, 9])

sparse_matrix = torch.sparse.IntTensor(i ,v, torch.Size([3, 3]))
print(sparse_matrix.to_dense())
row_idx = torch.tensor([0, 2])
col_idx = torch.tensor([0, 2])

selected = sparse_matrix.index_select(0, row_idx).index_select(1, col_idx).coalesce()
print(selected)
print(selected.to_dense())
selected.values().add_(1) # inplace 加1
print(selected.to_dense())
print(torch.LongTensor([row_idx.tolist(),col_idx.tolist()]))
sparse_matrix.index_put_((row_idx,col_idx),selected.to_dense())

print(sparse_matrix)
# SparseTensor(indices=tensor([[0, 0], [1, 1], [0, 2], [2, 0]]),  
#              values=tensor([2, 5, 8, 10]),
#              size=(3, 3), nnz=4, layout=torch.sparse_coo)